[package]
name = "visual-pcap"
version = "0.1.0"
authors = ["Eric Trombly <etrombly@yahoo.com>"]
edition = "2018"

[dependencies]
pcap = "0.7.0"
pnet = "0.25.0"
libc = "0.2.66"
chrono = "0.4.10"
ggez = "0.5.1"
legion = "0.2.1"
